### ISSUE TITLE
Typing in after with a cleared before error

### ISSUE THREAD

**Issue by TwoSummit** [samtrextom/postsam#4]
How to produce:  

1. Read url : https://tsdev.serigraph.com/scripts/data/dal/customer
2. hit x for read so that you have empty before and data in after
3. remove all but one entry in the after table
4. modify a value in the after table
5. wait
6. get error:
![image](https://user-images.githubusercontent.com/9383798/121417846-f4a48280-c92f-11eb-8f83-353496c55f60.png)

**Comment by Hoodiez13** [comment]
This error occurred when entering into the table JSON editor? Is it only reproduced when the Before editor was emptied?

**Comment by TwoSummit** [comment]
Correct, the issue only happens when the before editor was emptied

**Comment by Hoodiez13** [comment]
No longer applicable as 'react-json-editor-ajrm' is no longer in use.
